package com.aperise.mapper;

import com.aperise.bean.ProductProperty;
import com.aperise.bean.ProductPropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProductPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    long countByExample(ProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int deleteByExample(ProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int insert(ProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int insertSelective(ProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    List<ProductProperty> selectByExampleWithRowbounds(ProductPropertyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    List<ProductProperty> selectByExample(ProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    ProductProperty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProductProperty record, @Param("example") ProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByExample(@Param("record") ProductProperty record, @Param("example") ProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(ProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByPrimaryKey(ProductProperty record);
}