package com.aperise.mapper;

import com.aperise.bean.PropertyValue;
import com.aperise.bean.PropertyValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PropertyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    long countByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int deleteByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int insert(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int insertSelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    List<PropertyValue> selectByExampleWithRowbounds(PropertyValueExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    List<PropertyValue> selectByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    PropertyValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByExample(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByPrimaryKey(PropertyValue record);
}