package com.aperise.mapper;

import com.aperise.bean.Sku;
import com.aperise.bean.SkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    long countByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int deleteByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int insert(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int insertSelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    List<Sku> selectByExampleWithRowbounds(SkuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    List<Sku> selectByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    Sku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByExample(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByPrimaryKey(Sku record);
}