package com.aperise.mapper;

import com.aperise.bean.SkuProperty;
import com.aperise.bean.SkuPropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SkuPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    long countByExample(SkuPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int deleteByExample(SkuPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int insert(SkuProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int insertSelective(SkuProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    List<SkuProperty> selectByExampleWithRowbounds(SkuPropertyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    List<SkuProperty> selectByExample(SkuPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    SkuProperty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") SkuProperty record, @Param("example") SkuPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByExample(@Param("record") SkuProperty record, @Param("example") SkuPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByPrimaryKeySelective(SkuProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_property
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    int updateByPrimaryKey(SkuProperty record);
}