FROM tomcat

RUN rm -rf /usr/local/tomcat/webapps/*

#ADD sparklr-auth.war /tmp/
#RUN mv /tmp/sparklr-auth.war /usr/local/tomcat/webapps/sparklr-auth.war

ADD sparklr-auth.war /usr/local/tomcat/webapps/