package com.aperise.bean;

import java.util.Date;

public class Merchant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.name
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.display_name
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.gmt_create
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.gmt_modify
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.is_deleted
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.id
     *
     * @return the value of merchant.id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.id
     *
     * @param id the value for merchant.id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.name
     *
     * @return the value of merchant.name
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.name
     *
     * @param name the value for merchant.name
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.display_name
     *
     * @return the value of merchant.display_name
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.display_name
     *
     * @param displayName the value for merchant.display_name
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.gmt_create
     *
     * @return the value of merchant.gmt_create
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.gmt_create
     *
     * @param gmtCreate the value for merchant.gmt_create
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.gmt_modify
     *
     * @return the value of merchant.gmt_modify
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.gmt_modify
     *
     * @param gmtModify the value for merchant.gmt_modify
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.is_deleted
     *
     * @return the value of merchant.is_deleted
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.is_deleted
     *
     * @param isDeleted the value for merchant.is_deleted
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}