package com.aperise.bean;

import java.util.Date;

public class SkuProperty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_property.id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_property.sku_id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_property.property_id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private Integer propertyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_property.property_value_id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private Integer propertyValueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_property.gmt_create
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_property.gmt_modify
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_property.is_deleted
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_property.id
     *
     * @return the value of sku_property.id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_property.id
     *
     * @param id the value for sku_property.id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_property.sku_id
     *
     * @return the value of sku_property.sku_id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_property.sku_id
     *
     * @param skuId the value for sku_property.sku_id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_property.property_id
     *
     * @return the value of sku_property.property_id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_property.property_id
     *
     * @param propertyId the value for sku_property.property_id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_property.property_value_id
     *
     * @return the value of sku_property.property_value_id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public Integer getPropertyValueId() {
        return propertyValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_property.property_value_id
     *
     * @param propertyValueId the value for sku_property.property_value_id
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setPropertyValueId(Integer propertyValueId) {
        this.propertyValueId = propertyValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_property.gmt_create
     *
     * @return the value of sku_property.gmt_create
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_property.gmt_create
     *
     * @param gmtCreate the value for sku_property.gmt_create
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_property.gmt_modify
     *
     * @return the value of sku_property.gmt_modify
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_property.gmt_modify
     *
     * @param gmtModify the value for sku_property.gmt_modify
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_property.is_deleted
     *
     * @return the value of sku_property.is_deleted
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_property.is_deleted
     *
     * @param isDeleted the value for sku_property.is_deleted
     *
     * @mbg.generated Sat Sep 02 01:19:39 CST 2017
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}